# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

dist: trusty
language: rust
services: docker
sudo: required

env:
  global:
    - CRATE_NAME=jorup

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=aarch64-unknown-linux-gnu DISABLE_TESTS=1
    - env: TARGET=x86_64-apple-darwin
      os: osx

    # Linux
    - env: TARGET=arm-unknown-linux-gnueabi DISABLE_TESTS=1
    - env: TARGET=armv7-unknown-linux-gnueabihf DISABLE_TESTS=1
    # - env: TARGET=mips64-unknown-linux-gnuabi64 DISABLE_TESTS=1
    # - env: TARGET=mips64el-unknown-linux-gnuabi64 DISABLE_TESTS=1
    # - env: TARGET=powerpc64-unknown-linux-gnu DISABLE_TESTS=1
    # - env: TARGET=powerpc64le-unknown-linux-gnu DISABLE_TESTS=1
    - env: TARGET=x86_64-unknown-linux-musl

    # *BSD
    # - env: TARGET=x86_64-unknown-freebsd DISABLE_TESTS=1
    # - env: TARGET=x86_64-unknown-netbsd DISABLE_TESTS=1

before_install:
  - set -e
  - rustup self update

install:
  - rustup update stable
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  - provider: releases
    api_key:
      secure: bUihg7PtpmZEXFQ+ZEboeITPlK9zud4KrrMKaUmNg4dp7bjVRnqNHnrtlanMUZ62QMsvcgYZA6G4AmIM1HR9GDndXoMZ1yrhUYvdJxTHzOTIvT09z/Q6NngC0kro1tEAPONt75Gaeo2lvxVUt8RJ9ysyYJotTDldlHEmomp2QCUcvfrTStnp+ms0x6AA27YqEAQnZUjdIO633DKgQCnmrcuLvJWK//WScxUEw6l9iBvABzyEzVXYxlvh61Y+Mf1ejhcOlxsVBjRcD/iN3B9u2czpCeH+Y1eSVyIhLRq/KKXdaPVJkeyFMCMvFDVV0IaH5FTUtzgXIRoAtuHiSN2ts1UCBL3YZcXWepEF6VShbhiaNx+Xex30Ig6G3utG3ygMAxDRzItYIT2bJhVeQPY/uiaeMoB/q+AzG83OwdaKVQgBxJMl1vjPPrB329OY5UH20WzIOtbejDtT7XCtO08RXm2TuYPbF56QImTXwK1yTUQ0rRxRB0cycHmFytjL9ODpzug8T3qoZs2RzFcuDK5A3R/v4ZwXs50u406ercIuuVca+r5QjZuY7Q+dogLj/8/RCMPHiaFbA1sAlfMb56mEAxmX+dX7VfpLbhprN5a4p049SER8+appeF4p3jgTyXxuBpu0YSBQLRvylGwaSmIqcfK0aAoZkNwPDsEeh7OE0Bc=
    file_glob: true
    file: $CRATE_NAME-$TRAVIS_TAG-$TARGET
    on:
      condition: $TRAVIS_RUST_VERSION = stable
      tags: true
    skip_cleanup: true

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
